version: '3.3'

services:
   apachephp:
     image: php:7.4-apache
     working_dir: /var/www/html
     # this will map the wordpress files into the current directory 
     volumes:
       - .:/var/www/html
     ports:
       - "8080:80"
     restart: always
